### ISSUE TITLE
Can't run CLI

### ISSUE THREAD

**Issue by pique0822** [PrimerAI/blanc#19]
I installed `blanc` for pypi using the command:
`pip3 install blanc` 
as instructed but when I then try to use the CLI I get the following output
```
$> blanc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/blanc", line 5, in <module>
    from blanc.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blanc/__main__.py", line 231
    'when True, mask every `gap` tokens ('gap_mask' tokens at once) that are longer than `min_token_length`'
                                                 ^
SyntaxError: invalid syntax
```
I'm able to get the code to work through python otherwise however...

**Comment by OlegVasilyev4096** [comment]
Thanks! Silly bug, will update tomorrow
