### ISSUE TITLE
CLI error: name 'min_token_length_normal_tune' is not defined

### ISSUE THREAD

**Issue by KineticCookie** [PrimerAI/blanc#55]
Hey!
I am trying  the CLI, but it fails with
```
Traceback (most recent call last):
  File "/Users/user/.local/bin/blanc", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.local/pipx/venvs/blanc/lib/python3.8/site-packages/blanc/__main__.py", line 283, in main
    min_token_length_normal_tune=min_token_length_normal_tune,
NameError: name 'min_token_length_normal_tune' is not defined
```

How to reproduce:
1. install blanc (both pipx and pure venv result in error)
```
pipx install --python python3.8 blanc==0.3.3
or
pip install blanc==0.3.3
```
2. run the command from README.md
```
blanc help --gap 6 --doc "Jack drove his minivan to the bazaar to purchase milk and honey for his large family." --summary "Jack bought milk and honey."
```

**Comment by OlegVasilyev4096** [comment]
Thanks, yes, that's error, CLI was not updated. Will have update when get through new 2FA magic...

**Comment by OlegVasilyev4096** [comment]
Updated the package, sorry for delay - the season and troubles changing to API token upload ...
If no trouble I'd close this issue in a few days.

**Comment by KineticCookie** [comment]
Just checked, version `0.3.4` works as expected 🎉 
Thanks 👍
